version: '3'
services:
  elasticsearch:
    image: elasticsearch:latest
    ports:
     - "9200:9200"
     - "9300:9300"
    restart: always
    container_name: elasticsearch
    volumes:
     - /docker/elasticsearch/data:/usr/share/elasticsearch/data
  logstash:
    image: logstash:latest
    restart: always
    container_name: logstash
    volumes:
     - /docker/logstash/conf:/config-dir
     - /docker/logstash/plugin:/plugin
    command: logstash -f /config-dir/logstash.conf
  kibana:
    image: kibana:latest
    ports:
     - "5601:5601"
    restart: always
    container_name: kibana
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
     - elasticsearch
  search:
    image: search:latest
    build: ./publish
    ports:
     - "50088:50088"
    restart: always
    container_name: search
    volumes:
     - /docker/search/logfile:/publish/logfile
    command: dotnet MicroServer.dll